# Generated by Django 6.1.1 on 2026-09-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Адрес в URL')),
                ('summary', models.CharField(max_length=300, verbose_name='Кратко')),
                ('description', models.TextField(verbose_name='Подробное описание')),
                ('stack', models.CharField(max_length=200, verbose_name='Стек')),
                ('github_url', models.URLField(blank=True, verbose_name='Ссылка на GitHub')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['order'],
            },
        ),
    ]
