# Generated by Django 6.1.1 on 2026-09-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='drawing',
            field=models.CharField(blank=True, choices=[('plc_rack', 'Стойка ПЛК')], max_length=30, verbose_name='Чертёж'),
        ),
    ]
