# Generated by Django 6.1.1 on 2026-09-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=300, verbose_name='Учебное заведение')),
                ('details', models.CharField(max_length=300, verbose_name='Уровень, специальность')),
                ('year', models.PositiveIntegerField(verbose_name='Год окончания')),
            ],
            options={
                'verbose_name': 'Образование или курс',
                'verbose_name_plural': 'Образование и курсы',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('role', models.CharField(max_length=300, verbose_name='Кто я (одна строка)')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Город')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram (без @)')),
                ('github', models.CharField(blank=True, max_length=100, verbose_name='GitHub (логин)')),
                ('about', models.TextField(verbose_name='О себе')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профиль',
            },
        ),
    ]
