# Generated by Django 6.1.1 on 2026-09-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_drawing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='drawing',
            field=models.CharField(blank=True, choices=[('plc_rack', 'Стойка ПЛК'), ('pis_charts', 'Параметры и графики'), ('screen_recorder', 'Запись экрана')], max_length=30, verbose_name='Чертёж'),
        ),
    ]
