# Generated by Django 6.1.1 on 2026-10-01 02:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Адрес в URL')),
                ('kind', models.CharField(choices=[('book', 'Книга'), ('course', 'Видеокурс'), ('series', 'Сериал'), ('practice', 'Практика'), ('habit', 'Привычка')], max_length=20, verbose_name='Тип')),
                ('unit', models.CharField(choices=[('pages', 'страницы'), ('lessons', 'уроки'), ('episodes', 'серии'), ('minutes', 'минуты'), ('tasks', 'задачи')], max_length=20, verbose_name='Единица')),
                ('target_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Объём')),
                ('daily_target', models.PositiveIntegerField(blank=True, null=True, verbose_name='Норма в день')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата начала')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('status', models.CharField(choices=[('active', 'В процессе'), ('done', 'Выполнена'), ('paused', 'На паузе'), ('dropped', 'Брошена')], default='active', max_length=20, verbose_name='Статус')),
                ('is_public', models.BooleanField(default=False, verbose_name='Показывать на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
                'ordering': ['status', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('amount', models.PositiveIntegerField(verbose_name='Сколько')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Заметка')),
                ('note_is_private', models.BooleanField(default=False, verbose_name='Личная заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='goals.goal', verbose_name='Цель')),
            ],
            options={
                'verbose_name': 'Отметка',
                'verbose_name_plural': 'Отметки',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
