# Generated by Django 6.1.1 on 2026-10-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_initial_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='finished_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
    ]
