# Generated by Django 6.1.1 on 2026-09-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='drawing',
            field=models.CharField(blank=True, choices=[('data_gaps', 'Данные с дырами')], max_length=30, verbose_name='Чертёж'),
        ),
    ]
