# Generated by Django 6.1.1 on 2026-10-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_drawing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='drawing',
            field=models.CharField(blank=True, choices=[('data_gaps', 'Данные с дырами'), ('carts_loop', 'Тележки по кругу'), ('hydraulics', 'Гидравлика и энкодер')], max_length=30, verbose_name='Чертёж'),
        ),
    ]
