# Generated by Django 6.1.1 on 2026-09-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('company', models.CharField(max_length=200, verbose_name='Компания')),
                ('start', models.DateField(verbose_name='Начало')),
                ('end', models.DateField(blank=True, null=True, verbose_name='Окончание')),
                ('description', models.TextField(blank=True, verbose_name='Что делал')),
            ],
            options={
                'verbose_name': 'Место работы',
                'verbose_name_plural': 'Опыт работы',
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Группа')),
                ('skills', models.TextField(verbose_name='Навыки через запятую')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Группа навыков',
                'verbose_name_plural': 'Навыки',
                'ordering': ['order'],
            },
        ),
    ]
