# Generated by Django 6.1.1 on 2026-10-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_education_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='in_automation',
            field=models.BooleanField(default=False, verbose_name='Считать в стаже автоматизации'),
        ),
    ]
